OL-9816 add wait decorator and refactor resource class
lenovo/ansible.lenovo-tacp pull request #5
Opened 2020-06-02 13:52 UTC by mariusvigariu

2020-06-02 14:01 UTC, xmadsen approved these changes
LGTM

2020-06-02 21:02 UTC, patrickjennings requested changes

2020-06-02 21:02 UTC, patrickjennings commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +        allowed = ['==', '!=', '=lt=', '<', '=le=', '<=', '=gt=', '>', '=ge=',
Would recommend to pull this out as a field on the base class so that it may be easily overridden by the subclasses.

2020-06-02 21:02 UTC, patrickjennings commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +                    continue
If an op is not allowed, it seems that you should throw an exception instead of skip and continue.

2020-06-02 21:02 UTC, patrickjennings commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +    def wrapper(self, *a, **kws):
What about a kwarg `async` which is common to this annotation and is popped off here. It defaults to False, but if set to True, the action will not be waited upon?

2020-06-03 10:01 UTC, mariusvigariu commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +    def wrapper(self, *a, **kws):
You mean a kwarg which basically cancels the decorator's functionality? If I understood correctly, I dont see how that would help

2020-06-03 10:01 UTC, mariusvigariu commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +        allowed = ['==', '!=', '=lt=', '<', '=le=', '<=', '=gt=', '>', '=ge=',
Setting a class attribute out of this is fine with me, however these are all the operators in FIQL notation accepted by the api and I dont think subclasses would ever need to change them. In what scenarios do you think this is needed?

2020-06-03 10:01 UTC, mariusvigariu commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +                    continue
Initially I was thinking to just log some error message, but raising an exception would probably be better. Done.

2020-06-03 17:52 UTC, patrickjennings commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +        allowed = ['==', '!=', '=lt=', '<', '=le=', '<=', '=gt=', '>', '=ge=',
There is no use case right now. It only makes the method closed for extension in the future. Why do you want to keep the constant in the method?

2020-06-03 17:54 UTC, patrickjennings commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +    def wrapper(self, *a, **kws):
Yes. If you look at other cloud modules, they have `wait` variables which make the task not wait on the action. For example: https://docs.ansible.com/ansible/latest/modules/ec2_module.html#parameter-wait.
This does not wait by default.

2020-06-04 06:12 UTC, mariusvigariu commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +    def wrapper(self, *a, **kws):
Right, I see now. You want to emulate that kind of functionality with the hardcoded 60s below as `wait_timeout` and `wait` boolean to switch this on or off at runtime. Makes sense, I will adjust this accordingly

2020-06-04 06:12 UTC, mariusvigariu commented on lib/ansible/module_utils/tacp_ansible/tacp_utils.py
> +        allowed = ['==', '!=', '=lt=', '<', '=le=', '<=', '=gt=', '>', '=ge=',
And I dont think it will ever be. I dont not see any reason for a subclass to override the allowed operators, hence the local namespace variable. 

However I set it as class attribute and referenced it as a constant.

2020-06-04 12:49 UTC, patrickjennings approved these changes

2020-06-04 12:49 UTC, patrickjennings commented
LGTM

2020-06-04 12:50 UTC, merged